// Generated by scripts/inject-env.js at build time. DO NOT EDIT OR COMMIT.
window.ARENAX_SUPABASE_CONFIG = {
  url: "https://citefhwdgzuhtqtstvzq.supabase.co",
  anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdGVmaHdkZ3p1aHRxdHN0dnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MTY4MDIsImV4cCI6MjEwMDk5MjgwMn0.eBvpXAgE1DNAe_8o4Irprhybtcp25BiRzQqwDxSWiVc"
};
