/**
 * Writes js/config.js from environment variables at build time.
 *
 * Only the Supabase URL and the *anon* key are emitted -- both are safe in the
 * browser, since every table is protected by RLS and every balance-changing
 * operation goes through a SECURITY DEFINER function. The service role key must
 * never be referenced here.
 *
 * Netlify runs this via `npm run build`. Locally, `node scripts/inject-env.js`
 * picks the values up from .env.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'js', 'config.js');

// Local convenience: read .env when the vars are not already in the environment.
function loadDotEnv() {
  const file = path.join(ROOT, '.env');
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (!m) continue;
    const [, key, raw] = m;
    if (process.env[key]) continue;
    process.env[key] = raw.replace(/^["']|["']$/g, '');
  }
}

loadDotEnv();

const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';

if (!url || !anonKey) {
  console.warn(
    '[inject-env] SUPABASE_URL / SUPABASE_ANON_KEY are missing. ' +
    'Writing an empty config -- the marketplace will show a setup notice instead of live orders.'
  );
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `// Generated by scripts/inject-env.js -- do not edit, do not commit.\n` +
  `window.ARENAX_CONFIG = ${JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: anonKey }, null, 2)};\n`,
  'utf8'
);

console.log(`[inject-env] wrote ${path.relative(ROOT, OUT)} (supabase: ${url || 'unset'})`);
