import { TURN, SIDE, createInitialState, baselineFor, BOARD_SIZE, MARGIN, STRIKER_R, COIN_R } from './state.js';
import { Simulation } from './core/simulation.js';
import { isValidStrikerPlacement, findClearStrikerX } from './core/collision.js';

const s = createInitialState('ai', 'medium');
s.turn = TURN.P1; s.p1Side = SIDE.WHITE; s.p2Side = SIDE.BLACK;
const ownCoins = s.coins.filter(c => c.side === s.p1Side);
for (let i = 2; i < ownCoins.length; i++) ownCoins[i].active = false;
const target = ownCoins[0];
const pocket = { x: MARGIN + 10, y: MARGIN + 10 };
const baselineY = baselineFor(TURN.P1);
const uy = pocket.y - target.y;
const ux = pocket.x - target.x;
const t = (baselineY - target.y) / uy;
let sx = target.x + t * ux;
sx = Math.max(MARGIN + STRIKER_R + 2, Math.min(BOARD_SIZE - MARGIN - STRIKER_R - 2, sx));
console.log('target', target.x, target.y, 'sx', sx);
if (!isValidStrikerPlacement(sx, baselineY, s.coins)) sx = findClearStrikerX(baselineY, s.coins, sx);
console.log('clear sx', sx);
s.striker.x = sx; s.striker.y = baselineY;
const dx = target.x - pocket.x;
const dy = target.y - pocket.y;
const d = Math.hypot(dx, dy);
const gx = target.x + (dx / d) * (COIN_R + STRIKER_R + 0.5);
const gy = target.y + (dy / d) * (COIN_R + STRIKER_R + 0.5);
const dirX = gx - sx;
const dirY = gy - baselineY;
const dirLen = Math.hypot(dirX, dirY);
const speed = 520;
const sim = new Simulation(s);
sim.shoot((dirX / dirLen) * speed, (dirY / dirLen) * speed);
sim.runUntilSettled(5000);
console.log('pockets', sim.events.filter(e => e.type === 'pocket'));
console.log('final target active', target.active, target.x, target.y);
console.log('active coins', s.coins.filter(c => c.active).map(c => ({id:c.id, x:c.x.toFixed(0), y:c.y.toFixed(0), side:c.side})));
